### ISSUE TITLE
Is this Mars connecion option affect the artifical transaction control during autocommit set to true?

### ISSUE THREAD

**Issue by sogz2000** [MicrosoftDocs/sql-docs.zh-cn#115]
Recently we upgrading some legacy PowerBuilder application, we found that their transactions all set autocommit property to true, and also there are artifical control of transaction like "begin trans", commit and rollback trans found, they are work well in OLE DB connection, when we change them to SQL Native Client connection, all of these artifical transaction control will throw exception like "A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back". it can be fixed after adopt the provider's suggestion to add "MARS CONNECTION =FALSE" in the DBPARM, it seems conflict with the document in which MARS CONNECTION default to false, as we cannot found any document about this,can help us explain the mechanism between Mars connection and autocommit and different setting of MARS CONNECTION between SNC and OLE DB? thanks a lot

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 422aeb4a-f481-5c67-912c-6f4fd6414e30
* Version Independent ID: 55e1598c-3458-2701-c6b8-8255a0406f75
* Content: [使用多个活动结果集 (MARS) - SQL Server](https://docs.microsoft.com/zh-cn/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/native-client/features/using-multiple-active-result-sets-mars.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/relational-databases/native-client/features/using-multiple-active-result-sets-mars.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@David-Engel Hi David, Can you comment on this Issue 115?
Or should I ask @pmasl ?

CC: @WilliamAntonRohm

**Comment by David-Engel** [comment]
@MightyPen 

> they are work well in OLE DB connection, when we change them to SQL Native Client connection

SQL Native Client is an OLE DB provider and an ODBC driver in one library. So when they say "OLE DB connection" I'm not sure which OLE DB provider they are using. But I am going to assume they are referring to the Microsoft OLE DB Provider for SQL Server, which is the old original OLE DB provider included with Windows. **I would bet the Microsoft OLE DB Provider for SQL Server does not even support MARS** since MARS was introduced in 2005 and that provider pre-dates that.

Also, while MARS is defaulted to FALSE in SQL Native Client itself, their application may be setting it to TRUE by default behind the scenes (when the setting is available). Thus when they were using the Microsoft OLE DB Provider for SQL Server, there was no MARS setting for the application to set. Switching to SQL Native Client makes the MARS setting available to the application which is probably setting it to TRUE by default. Their fix of overriding the application's default setting for MARS when switching to a newer provider which supports it seems appropriate.

The error they are receiving:

> A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back

indicates that T-SQL they are running contains its own TRANSACTION commands (BEGIN TRAN, COMMIT, ROLLBACK), which the documentation notes will result in that behavior if the batch does not completely finish up it's transaction before finishing:

> Note
> A batch or stored procedure which starts a manual or implicit transaction when MARS is enabled must complete the transaction before the batch exits. If it does not, SQL Server rolls back all changes made by the transaction when the batch finishes. Such a transaction is managed by SQL Server as a batch-scoped transaction. This is a new type of transaction introduced in SQL Server 2005 (9.x) to enable existing well-behaved stored procedures to be used when MARS is enabled. For more information about batch-scoped transactions, see Transaction Statements (Transact-SQL).

**Comment by MightyPen** [comment]
@WilliamAntonRohm @msebolt Hi William and Matthew, Perhaps one of you can consider enhancing the documentation article a bit?

- _sogz2000 wrote:_ "conflict with the document in which MARS CONNECTION default to false,"

- _David-Engel wrote:_ "Switching to SQL Native Client makes the MARS setting available to the application which is probably setting it to TRUE by default."

We can discuss this at our next 2pm meeting. Just an idea, maybe there could be a non-Merged PR we could examine together? We'll see. Thanks.

**Comment by lichasu** [comment]
Hi @MightyPen, thanks for answering, what should I do with this issue? 

Thanks!

**Comment by David-Engel** [comment]
@MightyPen To clarify a bit, I was suggesting that the application itself was changing the value of the MARS setting (transparent to the user). The driver's default setting for MARS is accurately reflected in the documentation.

**Comment by MightyPen** [comment]
#assign:williamantonrohm

**Comment by MightyPen** [comment]
@lichasu Hello, It would be helpful if you can move or copy this Issue 115, from this repo= 'sql-docs.zh-cn' to English 'sql-docs'. Because in 'sql-docs' we have the necessary security authority to perform the various actions that we need to perform.
After the copy, this Issue 115 could then be Closed as a Duplicate, and further processing would occur with the English copy.

But if such a copy is difficult to perform, we will process this Issue 115 right here, and will @ notify you when we need certain actions performed.

Thanks.
GeneMi

**Comment by sogz2000** [comment]
Dear All:

     Appreciate your reply, since not found the relation between autocommit and Mars connection in formal document, Can I undstand that the issue of "A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back."  due to when Mars connection turn on, then autocommit transaction cannot allow manual conduct of transaction from begin to end(begin tran, commit, rollback), to allow artifact control in the same transaction with autocommit can only turn off Mars option?

**Comment by sogz2000** [comment]
if in a connection with autocommit setting to true, when below error hit:
"A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back"
Is this the best way to change to Mars connection to false? seems autocommit means all the DML statement will potential commit its transaction as end, Am I right?

**Comment by David-Engel** [comment]
@sogz2000 I don't believe it is related to the autocommit setting. MARS requires that only driver API methods are used to control transactions. Meaning OLE DB/ODBC API methods. If a transaction is started by the SQL statement(s) sent through the driver, it must be completed (committed/rolled back) by that same SQL statement(s). If a transaction is left open after a SQL statement is executed, and MARS is enabled, the error will be thrown, regardless of the autocommit setting. The application cannot rely on the autocommit setting to commit a transaction started within the SQL statement(s).

In your scenario, assuming that you were using a pre-MARS driver as I suspected, your best solution is to disable MARS via the connection string.

**Comment by MightyPen** [comment]
sogz2000 wrote the following, on 2019/July/17 18:57pm PDT. I copyu and paste a duplicate here because the original use of backticks make the original 18:57 text difficult to read:

> "Appreciate your reply, since not found the relation between autocommit and Mars connection in formal document, Can I undstand that the issue of "A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back."  due to when Mars connection turn on, then autocommit transaction cannot allow manual conduct of transaction from begin to end(begin tran, commit, rollback), to allow artifact control in the same transaction with autocommit can only turn off Mars option?"

**Comment by MightyPen** [comment]
@WilliamAntonRohm Hi William, Per your related email, the existing NOTE might be improved by the following additions (before the "From more info.....").

> By default, MARS functionality is not enabled. To use MARS when connecting to SQL Server with SQL Server Native Client, you must specifically enable it within a connection string. Some clients that use a pre-MARS driver might enable MARS by default. For these clients, you can disable MARS in the connection string as needed. For more information, see the SQL Server Native Client OLE DB provider and SQL Server Native Client ODBC driver sections, later in this topic.

Thanks. G

cc: @msebolt @David-Engel

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, please confirm the changes in https://github.com/MicrosoftDocs/sql-docs-pr/pull/11412.

cc: @MightyPen @msebolt

**Comment by David-Engel** [comment]
@WilliamAntonRohm I don't have access to the sql-docs-pr repo for a few more months. But if it's the quote from @MightyPen , I would edit that like this:

> By default, MARS functionality is not enabled by the driver. To use MARS when connecting to SQL Server with SQL Server Native Client, you must specifically enable it within a connection string. However, some applications may enable MARS by default, if the application detects that the driver supports it. For these applications, you can disable MARS in the connection string as needed. For more information, see the SQL Server Native Client OLE DB provider and SQL Server Native Client ODBC driver sections, later in this topic.

**Comment by MightyPen** [comment]
#please-close (Close this issue 115, because I lack the security authorization to close this.)

Fixed this Issue #115 with PR 11460.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/11460`

@sogz2000 Hello, The issue that you brought to our attention is now fixed. The fix will be live on Docs within 24 hours from now.
Therefore, I am now closing this issue. The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
Thank you for submitting this Issue. We hope to hear from you again.

@David-Engel Your help on this issue was extremely valuable. Thank you.

cc: @WilliamAntonRohm  

(GeneMi)
