### ISSUE TITLE
Column Definition Grammar Question

### ISSUE THREAD

**Issue by luomoyuyi** [MicrosoftDocs/sql-docs.zh-cn#139]
for the grammar 
&lt;column_definition&gt;::=
{
    column_name
    type_name [ ( precision [ , scale ] ) ]
    [ &lt;column_constraint&gt; ]
    [ COLLATE Windows_collation_name ]
    [ NULL | NOT NULL ]
}

Does it mean that "column_constraint" element (if exists) must be written ahead of "[ NULL | NOT NULL ]" element ? 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: abcca5d2-d433-96cc-930e-4de020c5785d
* Version Independent ID: fde147ff-b157-502c-276a-d3a2bf9bb3c7
* Content: [ALTER TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/zh-cn/sql/t-sql/statements/alter-table-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/t-sql/statements/alter-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by srvbpigh** [comment]
Hello, @luomoyuyi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @luomoyuyi, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/139. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
